sheet_name = "employee's info"
# "Реєстр :: Список підрядників"
# "employee's info"
google_folder = "1fGkO8AuLMJIN9gL-oVxWfZNS2rTQfMnp"
templates_folder = "1UszkdJsg2p68ZdJqicn7woWZbo6rXHjY"
signed_folder = "10vEfepjxEDVTxKrHcsdrDRhWyuFzmY0h"
personal_data_folder = "15EHAsoUx5qjYMAxZIWsMRBSzz5tbOWBr"
contract_folder = "1GChU2qvZ8T6eoQ3WiDL2Q5hinCunKxmR"
NDA_folder = "1gdWrsm6bJdMg-whC2eLyTCW73NmqIHp-"
